# Uncomment the next line to define a global platform for your project
 platform :ios, '14.3'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.0.0'

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appUITests' do
    # Pods for testing
  end

end
